### ISSUE TITLE
Can see the update in the gallery, but update doesn't stick.

### ISSUE THREAD

**Issue by gamagan** [msomeone/PeasyMotion#34]
Thank you for making the latest set of changes, which updates the extension to 1.9.*

Unfortunately, as mentioned in the release notes, I cannot update the extension to 1.9. I've tried all things I could, including disabling auto-updates, but problem is still there. I also uninstalled the extension, then tried to install from CI, but that one does not install, either. I get the following error:

![image](https://github.com/msomeone/PeasyMotion/assets/9970152/40b84d0f-9db6-4702-a315-cbce612389c2)

The one thing that jumps out at me is  "Extension is not signed."

```
2024-05-15 9:25:36 - Microsoft VSIX Installer
2024-05-15 9:25:36 - -------------------------------------------
2024-05-15 9:25:36 - vsixinstaller.exe version:
2024-05-15 9:25:36 - 17.10.2178+aee1612ae5
2024-05-15 9:25:36 - -------------------------------------------
2024-05-15 9:25:36 - Command line parameters:
2024-05-15 9:25:36 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,T:\DOWNLOADS\PeasyMotion v1.9(2).vsix
2024-05-15 9:25:36 - -------------------------------------------
2024-05-15 9:25:36 - Microsoft VSIX Installer
2024-05-15 9:25:36 - -------------------------------------------
2024-05-15 9:25:36 - Initializing Install...
2024-05-15 9:25:36 - Searching for applicable products...
2024-05-15 9:25:38 - Found installed product - Visual Studio Community 2022
2024-05-15 9:25:38 - Found installed product - Visual Studio Community 2022 Preview
2024-05-15 9:25:38 - Found installed product - Global Location
2024-05-15 9:25:38 - Extension Details...
2024-05-15 9:25:38 - 	Identifier         : PeasyMotion.a87d2837-6b54-4518-b014-3b29b4dcd902
2024-05-15 9:25:38 - 	Name               : PeasyMotion
2024-05-15 9:25:38 - 	Author             : Maksim Vorobiev
2024-05-15 9:25:38 - 	Version            : 1.9
2024-05-15 9:25:38 - 	Description        : Implements several vim-easymotion motions (word,line,two-char search), fast tab / document switching, fast text region selection.
This extension differs from other motion/jump extensions as it assigns jump labels to all words in text viewport, without asking specific "jump" key.
Such a behaviour may lead to faster motion and navigation in certain scenarios.
Inspired by vim-easymotion.
        
2024-05-15 9:25:38 - 	Locale             : en-US
2024-05-15 9:25:38 - 	MoreInfoURL        : 
2024-05-15 9:25:38 - 	InstalledByMSI     : False
2024-05-15 9:25:38 - 	SupportedFrameworkVersionRange : [4.5,)
2024-05-15 9:25:38 - 	SignatureState     : Unsigned
2024-05-15 9:25:38 - 	Supported Products : 
2024-05-15 9:25:38 - 		Microsoft.VisualStudio.Community
2024-05-15 9:25:38 - 			Version : [16.0,17.0)
2024-05-15 9:25:38 - 			ProductArchitecture : x86
2024-05-15 9:25:38 - 	References         : 
2024-05-15 9:25:38 - 	Prerequisites      : 
2024-05-15 9:25:38 - 		-------------------------------------------------------
2024-05-15 9:25:38 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2024-05-15 9:25:38 - 		Name         : Visual Studio core editor
2024-05-15 9:25:38 - 		Version      : [16.0,17.0)
2024-05-15 9:25:38 - Signature Details...
2024-05-15 9:25:38 - 	Extension is not signed.
2024-05-15 9:25:38 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by msomeone** [comment]
That's weird... 99% we can install without signing extension. If you have 2019 and 2022 VS, try uninstalling peasymotion in 2019, then 2022. And then install for 2022 only from https://ci.appveyor.com/project/msomeone/peasymotion/build/artifacts (for me, browser downloads extension as .zip file - rename to .vsix manually). That worked in my case. Let me know if this helps

**Comment by msomeone** [comment]
Btw, try uninstalling VS 2022 Preview, it seems like it`s still installed (log - "2024-05-15 9:25:38 - Found installed product - Visual Studio Community 2022 Preview").

**Comment by msomeone** [comment]
Btw, were you downloading from AppGallery here https://marketplace.visualstudio.com/items?itemName=maksim-vorobiev.PeasyMotion2022
or here https://marketplace.visualstudio.com/items?itemName=maksim-vorobiev.PeasyMotion ?

LOG says its "2024-05-15 9:25:38 - 	Version            : 1.9", which looks like PM for 2019 build...

That's fun - when i try downloading from matkerplace, the plugin version in vsix is 1.7.88... not 1.9 or 1.9.102. Somehow it's not updated on marketplace.
Gona try renaming packages and re-upload on market place.

**Comment by msomeone** [comment]
I've made old VS2022 plugin "private" on marketplace. Created new "PeasyMotion 2022" extension and page - https://marketplace.visualstudio.com/items?itemName=maksim-vorobiev.PeasyMotion2022newGUID

Look for PeasyMotion 2022 in "Extension Manager" or on marketplace. That one should work, even with auto-updates.

![image](https://github.com/msomeone/PeasyMotion/assets/783812/2339067e-1c7d-4cb9-a029-7d109525160b)

**Comment by gamagan** [comment]
Success! Oh lord have mercy -- this boy done did it! He done gon fixed a bunch of tasks, and now PeasyMotion is oiled up.  Hallelujah!
